# Generated by Django 4.1.5 on 2023-12-08 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kfp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('Category', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=50)),
                ('higher_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kfp.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('D_no', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=50, unique=True)),
                ('D_img', models.ImageField(null=True, upload_to='DishPng/')),
                ('description', models.TextField(max_length=500, null=True)),
                ('Cost', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kfp.categories')),
            ],
        ),
        migrations.CreateModel(
            name='DishesVariants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Variant_no', models.CharField(max_length=45)),
                ('count', models.DecimalField(decimal_places=2, default=1.0, max_digits=8)),
                ('Dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kfp.dishes')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('Order', models.IntegerField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.CreateModel(
            name='OrdersHasDishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.DecimalField(decimal_places=2, default=1.0, max_digits=8)),
                ('done', models.BooleanField(default=False)),
                ('Dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kfp.dishes')),
                ('Order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kfp.orders')),
                ('Variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kfp.dishesvariants')),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='waiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DishesProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=45)),
                ('weight', models.DecimalField(decimal_places=3, default=0.0, max_digits=8, null=True)),
                ('Dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kfp.dishes')),
            ],
        ),
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('Bill', models.IntegerField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('Cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kfp.orders')),
                ('waiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
