# Generated by Django 4.1.5 on 2023-12-17 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kfp', '0002_categories_dishes_dishesvariants_orders_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('Notification_no', models.IntegerField(primary_key=True, serialize=False)),
                ('notification', models.TextField(max_length=511)),
                ('status', models.IntegerField(choices=[(0, 'Info'), (1, 'Warning'), (2, 'End')])),
                ('To', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
