# Generated by Django 4.1.5 on 2024-01-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kfp', '0003_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordershasdishes',
            name='note',
            field=models.TextField(null=True, verbose_name=500),
        ),
    ]
