# Generated by Django 4.1.5 on 2024-01-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kfp', '0004_ordershasdishes_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordershasdishes',
            name='note',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
