# Generated by Django 4.1.5 on 2024-01-21 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kfp', '0006_orders_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='Order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kfp.orders'),
        ),
    ]
