# Generated by Django 4.1.5 on 2024-01-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kfp', '0007_notifications_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='Notification_no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
